{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "binary-compatibility-validator",
    "version": "0.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "binary-compatibility-validator-0.6.0-SNAPSHOT.jar",
          "url": "binary-compatibility-validator-0.6.0-SNAPSHOT.jar",
          "size": 137818,
          "sha512": "fe1638853ee7411e9414fc68839d349a914935ee2cf84cac71984003688d2ffd0f15c220c07ce2fcaf40acc4dacc170a26c1225c08c39e5feacadbe43748ff74",
          "sha256": "05685488be3a2c82bfd205cf1ff25706cd2af4ccdf643dcf2d5660df1bf0aba3",
          "sha1": "e9e1bc35f6053f95c4c3a8e33bfd486fcf4af9c1",
          "md5": "32ffe5347f81c8a2c610e509861eb56b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-metadata-jvm",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "com.googlecode.java-diff-utils",
          "module": "diffutils",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "binary-compatibility-validator-0.6.0-SNAPSHOT.jar",
          "url": "binary-compatibility-validator-0.6.0-SNAPSHOT.jar",
          "size": 137818,
          "sha512": "fe1638853ee7411e9414fc68839d349a914935ee2cf84cac71984003688d2ffd0f15c220c07ce2fcaf40acc4dacc170a26c1225c08c39e5feacadbe43748ff74",
          "sha256": "05685488be3a2c82bfd205cf1ff25706cd2af4ccdf643dcf2d5660df1bf0aba3",
          "sha1": "e9e1bc35f6053f95c4c3a8e33bfd486fcf4af9c1",
          "md5": "32ffe5347f81c8a2c610e509861eb56b"
        }
      ]
    }
  ]
}
