[versions]
# Used directly by ProjectPlugin
apiVersion = "2.3"
dateTime = "0.8.0"
dokka = "2.2.0"
jmh = "0.7.3"
jmh-core = "1.37"
benchmark = "0.4.17"
junit5-jupiter = "5.14.4"
junit-jupiter = "6.0.3"
kotlin = "2.4.0"
kotlinx-serialization = "1.11.0"
kotlinx-io = "0.9.0"
kxml2 = "2.3.0"
woodstox = "7.2.1"
xmlutil = "1.0.2-SNAPSHOT"
httpComponents5 = "5.6.1"
atomicfu = "0.33.0"
mockery = "3.4.2"

[libraries]
jmhCore = { module = "org.openjdk.jmh:jmh-core", version.ref = "jmh-core"}
kxml2 = { module = "net.sf.kxml:kxml2", version.ref = "kxml2" }
woodstox = { module = "com.fasterxml.woodstox:woodstox-core", version.ref = "woodstox" }

httpclient = { module = "org.apache.httpcomponents.client5:httpclient5", version.ref="httpComponents5" }

junit5-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5-jupiter" }
junit5-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5-jupiter" }

junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-jupiter" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }
junit-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit-jupiter" }

datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "dateTime" }
benchmark-runtime = { module = "org.jetbrains.kotlinx:kotlinx-benchmark-runtime", version.ref = "benchmark"}
serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-io-core = { module="org.jetbrains.kotlinx:kotlinx-io-core", version.ref="kotlinx-io" }
kotlinx-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
jmh = { id = "me.champeau.jmh", version.ref = "jmh" }
benchmark = { id = "org.jetbrains.kotlinx.benchmark", version.ref = "benchmark" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" }
mockery = { id = "dev.mokkery", version.ref = "mockery" }
